Repository Sedou932/Projet_versionning, pull requests merged in 2021-05, with the labels that each got.

#4 Feature
  nombre.py
Labels: enhancement

#5 Develop
  nombre.py
Labels: enhancement

#6 Ajout de la fonctionnalité affichant le carré du nombre
  LISEZMOI.md
  nombre.py
Labels: enhancement

#7 Ajout d'une fonctionnalité affichant le double
  nombre.py
Labels: enhancement

#8 Nous aurons besoin d'un fichier pour les regles de contribution
  CONTRIBUTE.md
Labels: documentation

#9 Develop
  CONTRIBUTE.md
  LISEZMOI.md
  nombre.py
Labels: documentation, enhancement, question

#10 Releases
  CONTRIBUTE.md
  LISEZMOI.md
  nombre.py
Labels: documentation, enhancement, question
